embarcacion\EmbarcacionBundle\Entity\Propietario:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombre:
            type: string
            length: 255
        apellido:
            type: string
            length: 255
        dni:
            type: string
            length: '15'
        telefono:
            type: string
            length: 255
        direccion:
            type: string
            length: 255
        email:
            type: string
            length: 255
        localidad:
            type: string
            length: 255
    lifecycleCallbacks: {  }
